uberParameters = {
    backGroundImage: '',
    foregroundImage: '',
    isTwoLayer: '',
    audioFile: '',
    hasAudio: '',
    animationType: '',
    backgroundAnimationType: '',
    roundCorners: '',
    biggerPost: '',
    staticPost: '',
    compSlideIn: '',
    motionBlur: '',
    quoteEnabled: '',
    quoteAuthor: '',
    quoteText: '',
    resolution: '',
    descriptor: '',
    outputPath: '',
    fontFamily: '',
    ccVersion: '',
    isAutoDoable: '',
    saveProject: '',
}