var langDict_ru = {
    browse: "Обзор",
    doIt: "Вперед",
    cancel: "Отмена",
    windowName: "CT_Quoter " + scriptVersion,
    templateLocation: "Шаблон",
    pathToTemplate: "Путь к шаблону:",
    ccVersion: "Версия Creative Cloud:",
    unsupportedCCVersion: "Эта версия Creative Cloud не поддерживается.",
    templateNote: "Укажите шаблон, соответствующий версии Creative Cloud.",
    selectTemplate: "Укажите проект-шаблон",
    automatic: "Автоматический режим",
    manual: "Ручной режим",
    automaticPath: "Путь к папке с файлами:",
    manualBGPath: "Задний план:",
    selectBGImage: "Выберите изображения для заднего плана",
    manualPostPath: "Передний план:",
    selectPostPath: "Выберите изображения для переднего плана",
    audioFilePath: "Звук:",
    selectAudioPath: "Выберите Аудио-файл",
    options: "Настройки",
    roundCorners: "Пост с закругленными краями",
    biggerPost: "Увеличенный пост",
    staticPost: "Пост без движения",
    compSlideIn: "Заезд снизу с Прозрачностью",
    quoteBox: "Цитата",
    quoteAuthor: "Автор цитаты:",
    quoteText: "Текст Цитаты:",
    quoteEnabled: "Цитата включена",
    outputPanel: "Вывод",
    outputPath: "Папка вывода:",
    outputPathNote: "Сначала выберите исходные файлы",
    descriptor: "Название",
    saveToOutput: "Сохранить проект в папку вывода",
    queueProject: "Добавить в очередь для экспорта",
    exportProject: "Экспортировать проект",
    chooseRenderer: "Экспорт через:",
    aeRenderer: "After Effects",
    ameRenderer: "Media Encoder (несовместим с настройкой 'Заезд снизу')",
    closeProject: "Закрыть проект по завершении",
    invalidAutoPath: "Неверная папка для автоматического режима.",
    invalidBGPath: "Неверный путь к изображению заднего плана.",
    invalidPostPath: "Неверный путь к изображению переднего плана.",
    invalidAudioPath: "Неверный путь к аудио-файлу.",
    missingQuoteText: "Отсутствует текст цитаты.",
    missingDescriptor: "Введите название проекта.",
    interface_settings: "Интерфейс",
    lang_en: "Английский",
    lang_ru: "Русский",
    help: "Помощь",
    cantCloseWhileQueued: "Проект должен оставаться открытым, чтобы завершить экспорт. Для закрытия, используйте Media Encoder.",
    audioFileTooLong: "Аудио файл слишком длинный.\n\nАудио файл не может быть дольше 40 секунд. Скрипт завержится и перезапустится.",
    saveManually: "Сохраните проект вручную, чтобы избежать уведомлений 'ПРОЕКТ ЗАБЛОКИРОВАН'.",
    ccVersionError: "Ошибка версии Creative Cloud.",
    rearrangingLayersError: "Ошибка при расположении слоев.",
    ameIncompatibleSlideIn: "Экспорт через Media Encoder несовместим с 'Заездом снизу с прозрачностью.'",
    enterOuputPath: "Пожалуйста укажите папку Вывода.",
    missingAutoFiles: "Файлы отсутствуют. Пожалуйста проверьте папку Автоматического режима.",
    animationType: 'Тип анимации:',
    profileImage: "Скриншот профиля:",
    postImage: "Скриншот публикации:",
    backGroundImageLabel: "Изображение для заднего фона:",
    photoLabel: "Фото:",
    documentLabel: "Документ:",
    webSiteScreenshot: "Скриншот веб-страницы:",
    foregroundImageLabel: "Изображение для переднего плана:",
    additionalSettings: "Дополнительные настройки:",
    scrollingBackground: "Проезд заднего фона",
    photoZoomBackground: "Zoom заднего фона",
    englishInterface: "Английский",
    russianInterface: "Русский (в разработке)",
    interfaceLabel: "Интерфейс:",
    magic: "Магия...",
    initProgress: "Подготовка",
    initAETemplate: "Подготовка шаблона",
    importFiles: "Импорт файлов",
    importAudio: "Импорт аудио",
    importBackground: "Импорт заднего фона",
    importForeground: "Импорт переднего плана",
    audioToTimeline: "Добавления аудио в композицию",
    backgroundToTimeline: "Добавление заднего фона в композицию",
    foregroundToTimeline: "Добавление переднего плана в композицию",
    setQuote: "Настройка цитаты",
    setWorkArea: "Настройка рабочей области",
    setSlideIn: "Настройка 'Заезда снизу'",
    saveProjectIfNeeded: "Сохранение проекта (если требуется)",
    defaultCommentText: "Это поле для комментария или цитаты. Это поле обязательно. Можно добавить много предложений.\n\nАбзацы поддерживаются. Если поле для Автора заполнено, убедитесь, что цитата длиннее.",
    defaultNameText: "Необязательное поле для автора, должности автора цитаты\nАбзацы поддерживаются",
    pickAnyFileFolder: "Выберите любой файл в папке",
    saveProjectAutoPath: "Сохранить проект в папку",
    saveProjectManualPath: "Сохранить проект в папку с 'Задним планом'",
    fbType: 'Facebook / По-умолчанию',
    photoType: 'Фото',
    docType: 'Документ',
    pageScrollType: 'Скролл страницы',
    pickAFolderLabel: 'Выбрать папку',
    orLabel: 'ИЛИ',
    pickFilesLabel: "Выбрать файлы",
    backButton: '<< Назад',
    clearButtonLabel: 'Очистить',
    swapLabel: 'Поменять местами',
    expamplePreviewLabel: 'Предпросмотр',
    translateButton: 'English',
    translateLabel: 'Язык',
    experimentalLabel: 'Экспериментальный',
    examplePreviewLabel: 'Образец',
    experimentalPreviewNote: '"Экспериментальный" работает только с PNG',
    examplePreviewNote: 'Только примерный образец',
    sourceFiles: 'Исходные файлы',
    helpButton: 'Помощь',
    helpDescription: 'Скрипт создает анимацию из изображений или сам собирает их из указанной папки.\n\nПоддерживаемые форматы: PNG, JPG, JPEG, PDF, MP3 и WAV.',
    chkTypeZoom: 'Фото Zoom',
    resFpsSettings: 'Разрешение / FPS',
    techOpts2: 'Доп. настройки',
    chkFastMode: '"Быстрый" режим'
};

var langDict_en = {
    browse: "Browse",
    doIt: "Start",
    cancel: "Cancel",
    windowName: "CT_Quoter " + scriptVersion,
    templateLocation: "Template Location",
    pathToTemplate: "Path to Template:",
    ccVersion: "Creative Cloud Version:",
    unsupportedCCVersion: "Unsupported CC Version",
    templateNote: "Please provide a path to the same version of the template.",
    selectTemplate: "Select a Template Project",
    automatic: "Automatic",
    manual: "Manual",
    automaticPath: "Automatic Path:",
    manualBGPath: "Background Image:",
    selectBGImage: "Select a Background image",
    manualPostPath: "Foreground Image:",
    selectPostPath: "Select a Post image",
    audioFilePath: "Audio File:",
    selectAudioPath: "Select an Audio file",
    options: "Options",
    roundCorners: "Post with Rounded Corners",
    biggerPost: "Bigger than usual Post",
    staticPost: "Post doesn't move",
    compSlideIn: "Video Slide-In with Transparency",
    quoteBox: "Quote Box",
    quoteAuthor: "Quote Author:",
    quoteText: "Quote Text:",
    quoteEnabled: "Quote Enabled",
    outputPanel: "Output",
    outputPath: "Output Path:",
    outputPathNote: "Please pick the source files first",
    descriptor: "Descriptor:",
    saveToOutput: "Save the project to Output Path",
    queueProject: "Queue Project for Render",
    exportProject: "Export Project",
    chooseRenderer: "Choose Renderer",
    aeRenderer: "After Effects Renderer",
    ameRenderer: "Media Encoder (not compatible with Video Slide-In)",
    closeProject: "Close the project after finish",
    invalidAutoPath: "Invalid 'Automatic' path.",
    invalidBGPath: "Invalid Background image path.",
    invalidPostPath: "Invalid Post image path.",
    invalidAudioPath: "Invalid Audio file path.",
    missingQuoteText: "Missing Quote text.",
    missingDescriptor: "Please enter project Descriptor.",
    interface_settings: "Interface",
    lang_en: "English",
    lang_ru: "Russian",
    help: "Help",
    cantCloseWhileQueued: "Can't close the project while the render is queued in After Effects. Use Media Encoder instead.",
    audioFileTooLong: "Audio file is too long.\n\nAudio can't be longer than 40 seconds. Script will stop and restart.",
    saveManually: "Please save the project manually to avoid 'project locked' alerts.",
    ccVersionError: "Creative Cloud Version Error",
    rearrangingLayersError: "Rearranging layers error",
    ameIncompatibleSlideIn: "Exporting with Media Encoder isn't compatible with 'Video Slide-In with Transparency.'",
    enterOuputPath: "Please enter Output Path",
    missingAutoFiles: "Missing files. Please check the Automatic Folder Path.",
    animationType: 'Animation Type',
    profileImage: "Profile Image:",
    postImage: "Post Image:",
    backGroundImageLabel: "Background Image:",
    photoLabel: "Photo:",
    documentLabel: "Document:",
    webSiteScreenshot: "Web site Screenshot:",
    foregroundImageLabel: "Foreground Image:",
    additionalSettings: "Additional Settings",
    scrollingBackground: "Scrolling Background",
    photoZoomBackground: "Photo Zoom Background",
    englishInterface: "English Interface",
    russianInterface: "Russian Interface (buggy)",
    interfaceLabel: "Interface:",
    magic: "Making Magic...",
    initProgress: "Initializing",
    initAETemplate: "Initializing AE Template",
    importFiles: "Importing files",
    importAudio: "Importing audio file",
    importBackground: "Importing background image",
    importForeground: "Importing foreground image",
    audioToTimeline: "Adding audio to composition",
    backgroundToTimeline: "Adding background to composition",
    foregroundToTimeline: "Adding foreground to composition",
    setQuote: "Setting up Quote box",
    setWorkArea: "Setting work area",
    setSlideIn: "Setting up 'Slide-In'",
    saveProjectIfNeeded: "Saving project if needed",
    defaultCommentText: "This is a comment / quote text field. Populate as necessary. This field is mandatory. Multiple sentences allowed.\n\nLine breaks are allowed. If Name field is populated make sure the Comment field is longer.",
    defaultNameText: "Optional Name Field, Description Field\nLine breaks are allowed",
    pickAnyFileFolder: "Pick any file in a folder",
    saveProjectAutoPath: "Save Project to 'Automatic' Path",
    saveProjectManualPath: "Save Project to 'Background Image' Path",
    fbType: 'Facebook / Document',
    photoType: 'Photo',
    docType: 'Document 2',
    pageScrollType: 'Page Scroll',
    pickAFolderLabel: 'Pick a Folder',
    orLabel: 'OR',
    pickFilesLabel: "Pick Files",
    backButton: '<< Back',
    clearButtonLabel: 'Clear',
    swapLabel: 'Swap',
    expamplePreviewLabel: 'Preview',
    translateButton: 'Русский язык',
    translateLabel: 'Language',
    experimentalLabel: 'Experimental',
    examplePreviewLabel: 'Example',
    experimentalPreviewNote: '"Experimental" only supports PNGs',
    examplePreviewNote: 'Just a reference preview',
    sourceFiles: 'Source Files',
    helpButton: 'Help',
    helpDescription: 'This script creates an animation from provided images or gathers them from a folder. Just try it!\n\nSupported files: PNG, JPG, JPEG, PDF, MP3, and WAV.',
    chkTypeZoom: 'Photo Zoom',
    resFpsSettings: 'Resolution / Frame Rate',
    techOpts2: 'Additional Settings',
    chkFastMode: '"Fast" Mode'
};


var current_locale = $.locale.substring(0, 2).toUpperCase()
var defaultLanguage = (current_locale == 'RU') ? "RU" : "EN";
var localDict = (defaultLanguage == "RU") ? langDict_ru : langDict_en;